# Generated by Django 5.0.4 on 2024-05-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_purchaseorder_seller_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
