# Generated by Django 5.1.3 on 2024-11-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_orderitem_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
