# Generated by Django 5.1.3 on 2024-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_remove_product_cost_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
