# Generated by Django 5.1.3 on 2025-01-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
