# Generated by Django 5.1.3 on 2025-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Shipped/Dispatched', 'Shipped/Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Returned', 'Returned'), ('On Hold', 'On Hold'), ('Backordered', 'Backordered'), ('Partially Shipped', 'Partially Shipped'), ('Awaiting Payment', 'Awaiting Payment'), ('Awaiting Fulfillment', 'Awaiting Fulfillment')], default='Confirmed', max_length=20),
        ),
    ]
