# Generated by Django 5.1.3 on 2025-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Shipped/Dispatched', 'Shipped/Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Returned', 'Returned'), ('On Hold', 'On Hold')], default='Pending', max_length=20),
        ),
    ]
