# Generated by Django 5.1.3 on 2025-02-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0015_serviceappointment_completion_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technician',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='leave_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='leave_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
