# Generated by Django 5.1.3 on 2025-02-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0018_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('age_in_years', models.IntegerField()),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=50)),
                ('screen_size', models.CharField(max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='tv_exchange_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='eapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('pickup_notes', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.address')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eapp.technician')),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eapp.tvexchange')),
            ],
        ),
    ]
