# Generated by Django 5.1.3 on 2025-02-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0020_alter_tvexchange_exchange_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepickup',
            name='pickup_notes',
        ),
        migrations.RemoveField(
            model_name='exchangepickup',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='exchangepickup',
            name='verification_notes',
        ),
        migrations.AddField(
            model_name='exchangepickup',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 3 PM)'), ('evening', 'Evening (3 PM - 6 PM)')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangepickup',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvexchange',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_pickup', max_length=20),
        ),
    ]
