# Generated by Django 5.1.3 on 2025-02-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0021_remove_exchangepickup_pickup_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepickup',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangepickup',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tvexchange',
            name='quality_check_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvexchange',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangepickup',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('technician_assigned', 'Technician Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='tvexchange',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Exchange Approved'), ('rejected', 'Exchange Rejected'), ('pending_pickup', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('quality_check', 'Quality Check In Progress'), ('quality_passed', 'Quality Check Passed'), ('quality_failed', 'Quality Check Failed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_review', max_length=20),
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_collected', 'Item Collected'), ('quality_check', 'Quality Check'), ('exchange_approved', 'Exchange Approved'), ('exchange_rejected', 'Exchange Rejected'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('exchange_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('quality_check_date', models.DateTimeField(blank=True, null=True)),
                ('quality_check_result', models.BooleanField(blank=True, null=True)),
                ('quality_check_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.customer')),
                ('exchange_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eapp.tvexchange')),
                ('new_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eapp.order')),
            ],
        ),
    ]
